### ISSUE TITLE
Analise do HTML feito em sala de aula.

### ISSUE THREAD

**Issue by MOVelasco** [PedroPauloGarcia/EstudoSalaDeAula#1]
Olá Pedro Paulo.

Estou olhando primeiro arquivo que fizemos na nossa primeira aula de HTML, e o seu documento html, está muito bem formatado e endentado, já que fizemos ele em Notepad++. 
**Uma observação:** as suas imagens estão na pasta raiz, e deveria esta em uma pasta. No exemplo feito em sala, eu criei uma pasta chamada: **"img"** de imagens;

**Comment by PedroPauloGarcia** [comment]
ok, corrigido.

**Comment by PedroPauloGarcia** [comment]
obrigado, ja resolvi
